FROM openjdk:8-jdk-alpine
VOLUME /tmp
ADD ./target/${project.build.finalName}.jar app.jar

ENV AUTOJOB_DB_TYPE=${AUTOJOB_DB_TYPE} \
    AUTOJOB_DB_URL=${AUTOJOB_DB_URL} \
    AUTOJOB_DB_USERNAME=${AUTOJOB_DB_USERNAME} \
    AUTOJOB_DB_PASSWORD=${AUTOJOB_DB_PASSWORD} \
    AUTOJOB_PASSWORD_ENCRYPT=${AUTOJOB_PASSWORD_ENCRYPT} \
    AUTOJOB_RSA_PUBLIC_KEY=${AUTOJOB_RSA_PUBLIC_KEY} \
    AUTOJOB_RSA_PRIVATE_KEY=${AUTOJOB_RSA_PRIVATE_KEY}

EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]

