spring:
  sql:
    init:
      platform: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: ${AUTOJOB_DB_URL}
    username: ${AUTOJOB_DB_USERNAME}
    password: ${AUTOJOB_DB_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  quartz:
    jdbc:
      platform: h2

server:
  port: ${AUTOJOB_SERVER_PORT:8080}   #端口号，如果有端口冲突请修改为其他值

autojob:
  password:
    encrypt: ${AUTOJOB_PASSWORD_ENCRYPT} #是否开启加密
  rsa:
    public_key: ${AUTOJOB_RSA_PUBLIC_KEY}
    private_key: ${AUTOJOB_RSA_PRIVATE_KEY}
