spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:51306/autojob?characterEncoding=utf-8&allowMultiQueries=true&&useAffectedRows=true&useSSL=false
    username: root
    password: ${AUTOJOB_MYSQL_PASSWORD}
  jpa:
    show-sql: true