spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: ${AUTOJOB_DB_TYPE}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  quartz:
    job-store-type: jdbc
    jdbc:
      platform: mysql
      initialize-schema: ALWAYS

autojob:
  password:
    encrypt: true #是否开启加密
  rsa:
    public_key: ${AUTOJOB_RSA_PUBLIC_KEY}
    private_key: ${AUTOJOB_RSA_PRIVATE_KEY}

ok:
  http:
    connect-timeout: 60
    read-timeout: 60
    max-idle-connections: 200
    keep-alive-duration: 300

logging:
  level:
    com:
      laysan:
        autojob: info
