spring:
  datasource:
    url: jdbc:mysql://47.100.3.180:51306/autojob?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: autojob
    password: ${AUTOJOB_MYSQL_PASSWORD}
  jpa:
    show-sql: true