spring:
  datasource:
    url: jdbc:mysql:/127.0.0.1:40016/autojob?characterEncoding=utf-8&allowMultiQueries=true&&useAffectedRows=true&useSSL=false
    username: admin
    password: 123456
  jpa:
    show-sql: true