spring:
  sql:
    init:
      platform: mysql
  datasource:
    url: ${AUTOJOB_DB_URL}
    username: ${AUTOJOB_DB_USERNAME}
    password: ${AUTOJOB_DB_PASSWORD}
  quartz:
    jdbc:
      platform: mysql
server:
  port: ${AUTOJOB_SERVER_PORT:8080}

autojob:
  password:
    encrypt: ${AUTOJOB_PASSWORD_ENCRYPT}
  rsa:
    public_key: ${AUTOJOB_RSA_PUBLIC_KEY}
    private_key: ${AUTOJOB_RSA_PRIVATE_KEY}
